name: "Build"

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: loostrum/rocm-installer@v0.2
        with:
          version: "7.2.0"
      - run: |
          cmake -S . -B build -DHIPDECOMP_BUILD_EXTRAS=1
          make -C build -j
