name: "AMD GPU"

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-amd:
    name: "AMD GPU"
    runs-on: hx370
    steps:
      - uses: actions/checkout@v6

      - name: Check GPU visibility
        run: amd-smi list

      - name: Build hipDecomp
        run: |
          arch=$(offload-arch | head -n 1)
          cmake -S . -B build -DHIPDECOMP_BUILD_EXTRAS=1 -DHIPDECOMP_BUILD_FORTRAN=1 -DHIPDECOMP_ENABLE_ROCTX=1 -DCMAKE_HIP_ARCHITECTURES=${arch}
          make -C build -j

      - name: Run C++ tests
        run: |
          mpirun -n 2 ./build/tests/cc/halo_test_R32
          mpirun -n 2 ./build/tests/cc/halo_test_R64
          mpirun -n 2 ./build/tests/cc/halo_test_C32
          mpirun -n 2 ./build/tests/cc/halo_test_C64
          mpirun -n 2 ./build/tests/cc/transpose_test_R32
          mpirun -n 2 ./build/tests/cc/transpose_test_R64
          mpirun -n 2 ./build/tests/cc/transpose_test_C32
          mpirun -n 2 ./build/tests/cc/transpose_test_C64

      - name: Run Fortran tests
        run: |
          mpirun -n 2 ./build/tests/fortran/halo_test_R32
          mpirun -n 2 ./build/tests/fortran/halo_test_R64
          mpirun -n 2 ./build/tests/fortran/halo_test_C32
          mpirun -n 2 ./build/tests/fortran/halo_test_C64
          mpirun -n 2 ./build/tests/fortran/transpose_test_R32
          mpirun -n 2 ./build/tests/fortran/transpose_test_R64
          mpirun -n 2 ./build/tests/fortran/transpose_test_C32
          mpirun -n 2 ./build/tests/fortran/transpose_test_C64
          
      - name: Run examples
        run: |
          mpirun -n 4 ./build/examples/cc/basic_usage/basic_usage
          mpirun -n 4 ./build/examples/cc/basic_usage/basic_usage_autotune
          mpirun -n 4 ./build/examples/cc/basic_usage/basic_usage
          mpirun -n 4 ./build/examples/cc/basic_usage/basic_usage_autotune
